version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.6.1

    steps:
      - checkout

      - run:
          name: Set environment variables
          command: |
            echo "NEXT_PUBLIC_BASE_URL=https://skillexpress.knowledgemission.kerala.gov.in/api" > .env

      - run:
          name: Create next.config.js
          command: |
            echo "const nextConfig = {" > next.config.js
            echo "  output: 'export'," >> next.config.js
            echo "  basePath: '/console'," >> next.config.js
            echo "  assetPrefix: '/console/'," >> next.config.js
            echo "};" >> next.config.js
            echo "module.exports = nextConfig;" >> next.config.js

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build Next.js app
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - ./out

  deploy:
    docker:
      - image: cimg/node:21.6.1

    steps:
      - attach_workspace:
          at: ./out

      - run:
          name: Install sshpass
          command: sudo apt-get update; sudo apt-get install sshpass

      - run:
          name: Copy dist folder to remote server
          command: |
            echo -e "$SSH_PASSWORD" | \
            sshpass -p '' scp -r -P $SSH_PORT ./out $SSH_USER@$SSH_HOST:/public_html/test
          environment:
            SSH_HOST: $SSH_HOST
            SSH_USER: $SSH_USER
            SSH_PORT: $SSH_PORT
            SSH_PASSWORD: $SSH_PASSWORD

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
